#ifndef VCOS_CORE_SIRIUS_CONFIG_H
#define VCOS_CORE_SIRIUS_CONFIG_H

#define VCOS_CONFIG_PLATFORM_INFO "SIRIUS"

#ifndef VCOS_CONFIG_LOG_OUTPUT
#define VCOS_CONFIG_LOG_OUTPUT VCOS_CONFIG_LOG_OUTPUT_PLATFORM_DEFINED
#endif

#endif /* VCOS_CORE_SIRIUS_CONFIG_H */
