#ifndef VCOS_CORE_DEFAULT_CONFIG_H
#define VCOS_CORE_DEFAULT_CONFIG_H

#ifndef VCOS_CONFIG_PLATFORM_INFO
#define VCOS_CONFIG_PLATFORM_INFO "NONE"
#endif

#ifndef VCOS_CONFIG_LOG_OUTPUT
#define VCOS_CONFIG_LOG_OUTPUT VCOS_CONFIG_LOG_OUTPUT_PLATFORM_DEFINED
#endif

#define VCOS_CONFIG_LOG_OUTPUT_NONE 0
#define VCOS_CONFIG_LOG_OUTPUT_DEBUG_UART 1
#define VCOS_CONFIG_LOG_OUTPUT_APP 2
#define VCOS_CONFIG_LOG_OUTPUT_PLATFORM_DEFINED 3

#ifndef VCOS_CONFIG_TSRB_UART_MEMORY_SIZE
#define VCOS_CONFIG_TSRB_UART_MEMORY_SIZE 128
#endif

#endif /* VCOS_CORE_DEFAULT_CONFIG_H */
