#ifndef VCOS_CORE_NET_DEFAULT_CONFIG_H
#define VCOS_CORE_NET_DEFAULT_CONFIG_H

#ifndef VCOS_NET_CONFIG_NUM_MESSAGE_BUFFERS
#define VCOS_NET_CONFIG_NUM_MESSAGE_BUFFERS 44
#endif

#ifndef VCOS_NET_CONFIG_MESSAGE_BUFFER_SIZE
#define VCOS_NET_CONFIG_MESSAGE_BUFFER_SIZE (sizeof(void *) * 32)
#endif

#endif /* VCOS_CORE_NET_DEFAULT_CONFIG_H */
